### ISSUE TITLE
Spielfeldbug

### ISSUE THREAD

**Issue by Jumieox** [SchoolHSBK/tictactoe#3]
Wenn man unter dem Fenster "Settings" bei der Größe des Spielfeldes eine Zahl <3 eingibt, und die aufkommende Fehlermeldung weg klickt, öffnet sich das MainWindow trotzdem mit der falsch angegebenen Spielfeldgröße.
Bei negativen Zahlen gibt's nen Overflow.

**Comment by Schwappi** [comment]
Stat: Issue reported.
Stat: Issue checked.
Priority: 4
Stat: Blocked 

Greetings
